server:
  port: 8488

# 数据库信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://203.91.78.89:3306/dtc_website
    username: root
    password: b0d569a5cc1f9717

# mybatis信息配置
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:dao/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
# 日志信息配置
logging:
  level:
    root: info
  file:
    name: comment.log
