server:
  port: 8488

# 数据库信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://203.91.78.89:3306/dtc_website
    username: root
    password: b0d569a5cc1f9717

# mybatis信息配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    数据库字段和实体类字段因为驼峰命名不一致问题解决方案
    map-underscore-to-camel-case: true
# 日志信息配置
logging:
  level:
    root: info
  file:
    name: comment.log
